name: CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GH_OAUTH }}

    steps:
      - uses: actions/checkout@v2

      - name: Replace toc-versions
        uses: Numynum/ToCVersions@master

      - name: Create Retail Package
        uses: BigWigsMods/packager@master
